### ISSUE TITLE
Support running both ClickHouse and ch-ui in same docker-compose project

### ISSUE THREAD

**Issue by pkazi** [caioricciuti/ch-ui#42]
### Idea Statement

Currently I am unable to run both ClickHouse and ch-ui in same docker-compose project.
ch-ui needs `VITE_CLICKHOUSE_URL` env variable to talk to ClickHouse DB.
- If used `http://localhost:8123`, it will work for UI in browser, as its UI's javascripts can access it from browser, but its not accessible within ch-ui's docker container, as it will check ch-ui's docker container for port 8123, which is not available, so UI will not render completely - 
![image](https://github.com/user-attachments/assets/07c32c07-278d-4307-8623-bba08a5331b6)
![image](https://github.com/user-attachments/assets/83d4dafa-b62a-4f5b-9310-462a911f25fb)

- If used `http://clickhouse:8123`, then its accessible within ch-ui's docker container, but browser is not aware of any clickhouse host
![image](https://github.com/user-attachments/assets/69789dc8-5a0a-487d-939a-f75b3fdee72e)

Here is my docker-compose file - 
```
services:
  clickhouse:
    image: clickhouse/clickhouse-server
    volumes:
      - ./.clickhouse_local_data:/var/lib/clickhouse
      - ./docker/dev.xml:/etc/clickhouse-server/users.d/dev.xml
    ports:
      - "9000:9000"
      - "8123:8123"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
  ch-ui:
    image: ghcr.io/caioricciuti/ch-ui:latest
    env:
      VITE_CLICKHOUSE_URL: "http://clickhouse:8123" # http://localhost:8123"
      VITE_CLICKHOUSE_USER: "admin"
      VITE_CLICKHOUSE_PASS: "password"
    restart: always
    ports:
      - "${CH_UI_PORT:-5521}:5521"
```

Need some way to support this use case.

**Workaround**
 - Add clickhouse host to local `/etc/hosts` file as - 
 ```
$ cat /etc/hosts
127.0.0.1	localhost clickhouse
```

**Comment by caioricciuti** [comment]
Hey, that's awesome! Thank you for bringing this up... What do you think is the most effective way to make this work? 

This should fit... 

```
version: '3.8'

services:
  ch-ui:
    image: ghcr.io/caioricciuti/ch-ui:latest
    restart: always
    ports:
      - "${CH_UI_PORT:-5521}:5521"
    environment:
      # Use localhost by default if no ClickHouse URL is specified
      VITE_CLICKHOUSE_URL: "${CLICKHOUSE_URL:-http://localhost:8123}"
      VITE_CLICKHOUSE_USER: "${CLICKHOUSE_USER:-}"
      VITE_CLICKHOUSE_PASS: "${CLICKHOUSE_PASS:-}"
    depends_on:
      - nginx # Ensure the UI starts only if the proxy is available
    networks:
      - app-network

  clickhouse:
    image: clickhouse/clickhouse-server
    volumes:
      - ./.clickhouse_local_data:/var/lib/clickhouse
      - ./docker/dev.xml:/etc/clickhouse-server/users.d/dev.xml
    ports:
      - "9000:9000"
      - "8123:8123"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    deploy:
      replicas: ${CLICKHOUSE_ENABLED:-0} # Default to 0 (disabled)

  nginx:
    image: nginx:alpine
    depends_on:
      - clickhouse
    ports:
      - "8123:8123" # Proxy to handle browser requests
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

```

and then... if you want to use with Clickhouse on the same docker-compose you can create a `nginx.conf` on the same folder and run as `CLICKHOUSE_ENABLED=1 docker-compose up` 

or  Running Only ch-ui (External ClickHouse) `docker-compose up`

Would this solve the issue?
