### ISSUE TITLE
Deploy in k8s

### ISSUE THREAD

**Issue by jonny-wg2** [caioricciuti/ch-ui#52]
### Idea Statement

Hi, any tips on getting this deployed in k8s? I attempted this and run into auth issues where it just won't connect.

deployment.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ch-ui
  namespace: clickhouse
  labels:
    app: ch-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ch-ui
  template:
    metadata:
      labels:
        app: ch-ui
    spec:
      containers:
        - name: ch-ui
          image: caioricciuti/ch-ui:latest
          ports:
            - containerPort: 5521
          env:
            - name: VITE_CLICKHOUSE_URL
              value: "http://clickhouse-cluster.clickhouse.svc.cluster.local:8123"
            - name: VITE_CLICKHOUSE_USER
              value: "chui"
            - name: VITE_CLICKHOUSE_PASS
              valueFrom:
                secretKeyRef:
                  name: clickhouse
                  key: CHUI_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: ch-ui
spec:
  type: ClusterIP
  ports:
    - port: 5521
      targetPort: 5521
      protocol: TCP
  selector:
    app: ch-ui
```

### Feature implementation brainstorm

Example documentation on getting this deployed in kubernetes.
