### ISSUE TITLE
connect to clickhouse in docker container on same docker network fails

### ISSUE THREAD

**Issue by robinpecha** [caioricciuti/ch-ui#55]
### Environment

Docker

### How did you encounter the bug?

Hi, Im running ch and ch-ui in docker:
```

services:

  clickhouse:
    container_name: mynetwork-clickhouse
    image: clickhouse/clickhouse-server:25.1-alpine 
    restart: always
    environment:
        CLICKHOUSE_USER: "user"
        CLICKHOUSE_PASSWORD: "admin"
    ports:
      - "9000:9000"
      - "8123:8123"
    networks:
      - mynetwork
    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - IPC_LOCK
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD", "clickhouse-client", "--host", "localhost", "--query", "SELECT 1"]
      interval: 30s
      timeout: 10s
      retries: 3        
    volumes:
      - /srv/data/mynetwork-clickhouse/var_lib_clickhouse/:/var/lib/clickhouse/ #data
      - /srv/data/mynetwork-clickhouse/var_log_clickhouse-server/:/var/log/clickhouse-server/ #logs
      - /srv/data/mynetwork-clickhouse/etc_clickhouse-server_config.d/:/etc/clickhouse-server/config.d/ #configs
      - /srv/data/mynetwork-clickhouse/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/ #init sql command


  clickhouse-ui:
    container_name: mynetwork-clickhouse-ui
    image: ghcr.io/caioricciuti/ch-ui:latest
    networks:
      - mynetwork
    ports:
      - "5521:5521"
    depends_on:
      - clickhouse
    environment:
      VITE_CLICKHOUSE_URL: "http://mynetwork-clickhouse:8123"
      VITE_CLICKHOUSE_USER: "user"
      VITE_CLICKHOUSE_PASS: "admin"


networks:
    mynetwork:
        external: true
        name: mynetwork      
```

### What did you expect?

That it connects to clickhouse in docker, something like this. But this instance of ch-ui is connected to different machine (10.10.10.70) with different db

![Image](https://github.com/user-attachments/assets/700c578b-de36-4a8c-91a3-181138f0577f)

### Actual Result

But it fails. Its not able to connect to clickhouse in the same docker instance:

![Image](https://github.com/user-attachments/assets/8b93465a-ac51-4255-976d-dc7e7f829075)

Nor with container IP:
![Image](https://github.com/user-attachments/assets/bda23c90-07d7-462b-8529-960564b9e835)

But from the CH-UI container I am able to see the Clickhouse container:
![Image](https://github.com/user-attachments/assets/b5cbb04f-14ff-4806-928b-e4aa5b17753f)

### Browser

Chrome

### Browser Version

latest chrome/vivaldi 7 and latest firefox 134

### Version

latest from docker repo

**Comment by caioricciuti** [comment]
Hey, hope all is good. 

Hmm, I don't see anything off with your config but since the image is working when I test it, I also don't see how it can be CH-UI's issue... So, let's try to make a little docker debug to see where it fails... 

connectivity between containers:
```bash
docker exec mynetwork-clickhouse-ui curl -v http://mynetwork-clickhouse:8123
```
ClickHouse is accepting external connections:
```bash
docker exec mynetwork-clickhouse cat /etc/clickhouse-server/config.d/*
```
network setup:
```bash
docker network inspect mynetwork
```
direct connection from UI container:
```bash
docker exec mynetwork-clickhouse-ui wget -O- http://mynetwork-clickhouse:8123
```

Give it a try or post the results and we can investigate further...

**Comment by trevor-qualified** [comment]
Hi @caioricciuti, I'm getting the same issue attempting to run ch-ui in a docker container within the same docker network as a clickhouse container. Loading the UI on my local machine I've tried every combination of dns/ips and ports to get this to work. 

I currently have clickhouse configured to map the exposed port 10300 to the internal port 8123. When I navigate to http://localhost:10300 on my local machine the page loads showing 'Ok.' as expected. 

Results of running `docker exec ch-ui curl -v http://clickhouse-1:8123`:
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Host clickhouse-1:8123 was resolved.
* IPv6: (none)
* IPv4: 192.168.97.30
*   Trying 192.168.97.30:8123...
* Connected to clickhouse-1 (192.168.97.30) port 8123
* using HTTP/1.x
> GET / HTTP/1.1
> Host: clickhouse-1:8123
> User-Agent: curl/8.11.1
> Accept: */*
> 
* Request completely sent off
< HTTP/1.1 200 OK
< Date: Wed, 05 Feb 2025 20:04:30 GMT
< Connection: Keep-Alive
< Content-Type: text/html; charset=UTF-8
< Transfer-Encoding: chunked
< Keep-Alive: timeout=30
< X-ClickHouse-Summary: {"read_rows":"0","read_bytes":"0","written_rows":"0","written_bytes":"0","total_rows_to_read":"0","result_rows":"0","result_bytes":"0"}
< 
{ [14 bytes data]
100     4    0     4    0     0    855      0 --:--:-- --:--:-- --:--:--  1000
* Connection #0 to host clickhouse-1 left intact
Ok.
```

Config.d files in clickhouse container:
`/etc/clickhouse-server/config.d/clickhouse-1.xml`:
```
<?xml version="1.0"?>
<!--
  ClickHouse server configuration specific to replica 'clickhouse-1'. See docker-compose.yml
-->
<yandex>
  <display_name>clickhouse-1</display_name> <!-- Name shown in clickhouse-client -->

  <!--
    Substitutions for parameters of replicated tables.
    See https://clickhouse.tech/docs/en/engines/table-engines/mergetree-family/replication/#creating-replicated-tables
  -->
  <macros>
    <cluster>local</cluster>
    <shard>01</shard>
    <replica>clickhouse-1</replica>
  </macros>
</yandex>
```

`/etc/clickhouse-server/config.d/docker_related_config.xml`:
```
<clickhouse>
     <!-- Listen wildcard address to allow accepting connections from other containers and host network. -->
    <listen_host>::</listen_host>
    <listen_host>0.0.0.0</listen_host>
    <listen_try>1</listen_try>

    <!--
    <logger>
        <console>1</console>
    </logger>
    -->
</clickhouse>
```

Results of running `docker network inspect network`:
```
[
    {
        "Name": "network",
        "Id": "503eb03ed27b8526f3a1904050af5bc18b9cd18453333c109f8ce7dc2cbde858",
        "Created": "2025-01-31T11:52:35.966448503-08:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "192.168.97.0/24",
                    "Gateway": "192.168.97.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "2ab9e7c039e2a425cd04b48fefa4fd5579cd9ece5c8bdf731871b08b6692b755": {
                "Name": "ch-ui",
                "EndpointID": "1ca86c07a576c03cd1768fb491f1051d0d03fa686878aa8f44102c96efacddae",
                "MacAddress": "02:42:c0:a8:61:20",
                "IPv4Address": "192.168.97.32/24",
                "IPv6Address": ""
            },
            "fb108363a2ffa594e34bd7dc358cc47e9c28808d2a3567634fb73cacd6f25389": {
                "Name": "clickhouse-1",
                "EndpointID": "b3aa527139b346d63e3de0b462b27ad0a2a0e123d2bf66d3e798ab14048f6450",
                "MacAddress": "02:42:c0:a8:61:1e",
                "IPv4Address": "192.168.97.30/24",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {
            "com.docker.compose.config-hash": "4c16b412f5586486f635defb45e0b2beda293bb42a4688c09741bedf28c4b4a3",
            "com.docker.compose.network": "default",
            "com.docker.compose.project": "fireball",
            "com.docker.compose.version": "2.32.4"
        }
    }
]
```

Results of running `docker exec ch-ui wget -qO- http://clickhouse-1:8123`: 'Ok.'

**Comment by morteza1131** [comment]
As I mentioned it in [this issue](https://github.com/caioricciuti/ch-ui/issues/52#issuecomment-2614025620) before, this is because how ch-ui implemented, network requests to Clickhose server are from client browser not docker container, and being in same network does not help at all.

https://github.com/caioricciuti/ch-ui/issues/52#issuecomment-2630271931

**Comment by caioricciuti** [comment]
@morteza1131 I believe you are right, but I'm not quite sure how to handle this, since this is a client only app and uses the client package for connecting to click house...

**Comment by aziz-marashly** [comment]
> [@morteza1131](https://github.com/morteza1131) I believe you are right, but I'm not quite sure how to handle this, since this is a client only app and uses the client package for connecting to click house...

Thank you for your reply. I think what we do expect is to have something like PhpMyAdmin behavior. As the server is doing the request instead of UI. It is a security issue to keep the main port open for the public to connect the tool. Is it possible to do the request on the server?

**Comment by indigo423** [comment]
Here is how I have solved this problem, I have the ch-ui and clickhouse in the same compose.yml file on the same network.

Step 1: I have published the port 8123:8123/tcp on clickhouse to make it accessible on my docker host.
```yaml
services:
  clickhouse:
    image: clickhouse/clickhouse-server
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_DB: my-clickhouse-db
    volumes:
      # Store data to HDD
      - ./clickhouse-data:/var/lib/clickhouse/
      # Base Clickhouse cfg
      - ./clickhouse/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./clickhouse/users.xml:/etc/clickhouse-server/users.d/users.xml
    ports:
      - "8123:8123/tcp"
      - "9000:9000/tcp"
```

Step 2: Instead of using the internal IP or service name as VITE_CLICKHOUSE_URL, I have used the IP address of the Docker host.

```yaml
services:
...
  ch-ui:
    image: ghcr.io/caioricciuti/ch-ui:latest
    environment:
      VITE_CLICKHOUSE_URL: http://my-docker-host-ip-or-fqdn:8123
      VITE_CLICKHOUSE_USER: default
      VITE_CLICKHOUSE_PASS: ""
    ports:
      - "5521:5521/tcp"
```
