### ISSUE TITLE
Error: Connection failed (Invalid or missing ClickHouse credentials)

### ISSUE THREAD

**Issue by mbUSC** [caioricciuti/ch-ui#57]
### Environment

Docker

### How did you encounter the bug?

Hi team,

I am able to access my DB with the clickhouse client without any problems, but I'm running into this error when opening ch-ui: `Connection failed. Credentials have been cleared`.

In the dev console, I can see this:
`Invalid or missing ClickHouse credentials:`
```json
{
    "customPath": "",
    "password": "",
    "requestTimeout": 30000,
    "url": "",
    "useAdvanced": false,
    "username": ""
}
```

I double-checked that the `VITE_CLICKHOUSE_URL`, `VITE_CLICKHOUSE_USER`, and `VITE_CLICKHOUSE_PASS` in the `docker-compose.yml` file are correct.

While researching a solution, I saw that another user had the same problem but never got an answer:
https://www.reddit.com/r/Clickhouse/comments/1hrt2z0/update_chui_opensource_clickhouse_query_interface/

Could you please help?

<img width="1127" alt="Image" src="https://github.com/user-attachments/assets/095d5a58-1a7d-4a12-a9e9-6fc969f60a8c" />

### What did you expect?

I was expecting to be able to log in

### Actual Result

I cannot log in

### Browser

Safari

### Browser Version

Version 18.4 (20621.1.15.11.8)

### Version

```
REPOSITORY                                                               TAG       IMAGE ID       CREATED        SIZE
ghcr.io/caioricciuti/ch-ui                                               latest    81f1fb13fdee   6 days ago     193MB
```

**Comment by condrove10** [comment]
do you have SSL/TLS enabled on your clickhouse server instance? @mbUSC

**Comment by iankressin** [comment]
+1

I'm having that exact same problem whenever I setup environment variables in my docker compose or when running the docker image directly.

**Comment by mbUSC** [comment]
@condrove10 Yes. 
I'm actually using TLS/SSL when connecting to the DB with `clickhouse-connect` as well, and that has always worked fine

**Comment by condrove10** [comment]
In that case you have to add your CA to your store. For example on Linux(Ubuntu/Debian):
```bash
sudo cp your_ca_root.crt /usr/local/share/ca-certificates/your_ca_root.crt
sudo chmod 644 /usr/local/share/ca-certificates/your_ca_root.crt
sudo update-ca-certificates
```

---
this way your browser add to it's store the certificate and you good to go! @mbUSC

**Comment by condrove10** [comment]
I suppose you use some reverse proxy with SSL/TLS (like Traefik) ? @iankressin

**Comment by condrove10** [comment]
### This is how I've setup mine:

```yaml
version: "3.9"
services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest-alpine
    restart: unless-stopped
    volumes:
      - /opt/clickhouse/config.xml:/etc/clickhouse-server/config.xml
      - /var/opt/clickhouse/data:/var/lib/clickhouse
      - /var/opt/clickhouse/logs:/var/log/clickhouse-server
    ulimits:
      nofile:
        hard: 262144
        soft: 262144
    container_name: clickhouse
    environment:
      - CLICKHOUSE_PASSWORD=<password>
      # - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
      - CLICKHOUSE_USER=root
      - CLICKHOUSE_DB=clickhouse
    cap_add:
      - SYS_NICE # For adjusting process priorities
      - NET_ADMIN # For advanced network configurations
      - IPC_LOCK # For locking memory pages (mlock)
    networks:
      - traefik
      - clickhouse
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.clickhouse.rule=HostSNI(`clickhouse.msipro.local`)"
      - "traefik.tcp.routers.clickhouse.entrypoints=websecure"
      - "traefik.tcp.routers.clickhouse.service=clickhouse"
      - "traefik.tcp.routers.clickhouse.tls=true"
      - "traefik.tcp.services.clickhouse.loadbalancer.server.port=9000"
      - "traefik.http.routers.clickhouse-http.rule=Host(`clickhouse-http.msipro.local`)"
      - "traefik.http.routers.clickhouse-http.entrypoints=websecure"
      - "traefik.http.routers.clickhouse-http.service=clickhouse-http"
      - "traefik.http.routers.clickhouse-http.tls=true"
      - "traefik.http.services.clickhouse-http.loadbalancer.server.port=8123"
  ch-ui:
    image: ghcr.io/caioricciuti/ch-ui:latest
    dns:
      - "10.220.0.250"
    restart: unless-stopped
    environment:
      VITE_CLICKHOUSE_URL: "https://clickhouse-http.msipro.local"
      VITE_CLICKHOUSE_USER: "root"
      VITE_CLICKHOUSE_PASS: "<password>"
      # Advanced Options
      VITE_CLICKHOUSE_USE_ADVANCED: "true" # Enable advanced features
      # VITE_CLICKHOUSE_CUSTOM_PATH: "/custom/path"  # Optional: Custom HTTP path
      VITE_CLICKHOUSE_REQUEST_TIMEOUT: "30000" # Optional: Request timeout in milliseconds
    labels:
      - traefik.enable=true
      - traefik.http.routers.chu.rule=Host(`chu.msipro.local`)
      - traefik.http.routers.chu.entrypoints=web,websecure
      - traefik.http.routers.chu.service=chu
      - traefik.http.routers.chu.tls=true
      - traefik.http.services.chu.loadbalancer.server.port=5521
      - traefik.http.services.chu.loadbalancer.passhostheader=true
    networks:
      - clickhouse
      - traefik
networks:
  clickhouse: {}
  traefik:
    external: true
```

### And have my Root CA to in my client machine CA store:

---

<img width="959" alt="Image" src="https://github.com/user-attachments/assets/05fffba2-ec89-4959-8a5d-fc41ac77cdbf" />
