### ISSUE TITLE
Query Results for Tuples and JSON are not displayed correctly.

### ISSUE THREAD

**Issue by jeevanragula** [caioricciuti/ch-ui#60]
### Environment

Docker

### How did you encounter the bug?

1. Run the docker compose and connect to Clickhouse cluster

```
ch-ui:
    image: ghcr.io/caioricciuti/ch-ui:latest
    restart: always
    ports:
      - "5521:5521"
    environment:
      VITE_CLICKHOUSE_URL: "http://localhost:8123"
```
2. Go to query editor and execute the query and check the results in table viewer.

### What did you expect?

The Fields for Array, Tuple and JSON should be rendered correctly in readable form.
But they are displayed just as Objects.

But this is displayed correct if we go to sample data screen.

![Image](https://github.com/user-attachments/assets/11c48467-1720-4f03-b7a2-9b1a88c31d48)
![Image](https://github.com/user-attachments/assets/0f944ba4-1e30-4385-a651-b03461d1a85a)

### Actual Result

The Fields for Array, Tuple and JSON should be rendered correctly in readable form.
But they are displayed just as Objects.

But this is displayed correct if we go to sample data screen.

![Image](https://github.com/user-attachments/assets/11c48467-1720-4f03-b7a2-9b1a88c31d48)
![Image](https://github.com/user-attachments/assets/0f944ba4-1e30-4385-a651-b03461d1a85a)

### Browser

Chrome

### Browser Version

Version 134.0.6998.167 (Official Build) (arm64)

### Version

image: ghcr.io/caioricciuti/ch-ui:latest
