### ISSUE TITLE
docker-compose example misleading

### ISSUE THREAD

**Issue by AndriiSushko** [caioricciuti/ch-ui#62]
### Environment

Docker

### How did you encounter the bug?

Below docker-compose (inspired by readme) do not actually supply env correctly, resulting in: 

```
Invalid or missing ClickHouse credentials: 
{url: '', username: '', password: '', useAdvanced: false, customPath: '', …}
```

VITE_CLICKHOUSE_URL, VITE_CLICKHOUSE_USER, and VITE_CLICKHOUSE_PASS are runtime env vars. That won’t work unless the app is reading them dynamically at runtime, which most Vite apps don’t.
 

```
services:
  postgres:
    image: postgres:16.3-alpine3.19
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
    volumes:
      - ./postgres/pg_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
  clickhouse:
    image: clickhouse/clickhouse-server:25.4
    ports:
      - 9000:9000
      - 8123:8123
      - 8443:8443
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=test
  clickhouse-ui:
    image: ghcr.io/caioricciuti/ch-ui:latest
    restart: always
    ports:
      - 5521:5521
    environment:

      - VITE_CLICKHOUSE_URL=http://clickhouse:8123
      - VITE_CLICKHOUSE_USER=default
      - VITE_CLICKHOUSE_PASS=test

    depends_on:
      - clickhouse


```

### What did you expect?

Application runs 

### Actual Result

Invalid or missing ClickHouse credentials: 
{url: '', username: '', password: '', useAdvanced: false, customPath: '', …}

### Browser

Chrome

### Browser Version

-

### Version

latest

**Comment by sskf** [comment]
+1

**Comment by tcaty** [comment]
@AndriiSushko when you run ch-ui via docker compose like this your browser tries to connect to `VITE_CLICKHOUSE_URL=http://clickhouse:8123`, but there is no any information about `clickhouse` hostname on your local machine, you can't just open `http://clickhouse:8123` in browser, cause hostname `clickhouse` can be resolved only inside docker network. In order to connect to clickhouse from your browser you should open `http://localhost:8123/`, therefore you should specify this address for ch-ui as well.

So the valid compose file should be like this
```
services:
  clickhouse:
    image: clickhouse:25.4
    container_name: clickhouse
    environment:
      CLICKHOUSE_PASSWORD: admin
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
  
  ch-ui:
    image: ghcr.io/caioricciuti/ch-ui:latest
    container_name: ch-ui
    environment:
      VITE_CLICKHOUSE_URL: http://localhost:8123
      VITE_CLICKHOUSE_USER: default
      VITE_CLICKHOUSE_PASS: admin
    ports:
      - "5521:5521"

volumes:
  clickhouse-data:
```
