### ISSUE TITLE
CH-UI Cannot Connect to ClickHouse with Traefik Reverse Proxy Setup

### ISSUE THREAD

**Issue by bo-unitysvc** [caioricciuti/ch-ui#65]
### Environment

Docker

## Environment
- Docker Compose with Traefik as reverse proxy (with SSL)
- ClickHouse server running at `clickhouse-db.mycompany.com` (working correctly)
- Company network setup with multiple services

1. Docker compose file (without traefik labels)

```yaml
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    restart: always
    environment:
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - ./clickhouse_conf:/etc/clickhouse-server/conf.d
      - ./clickhouse_conf/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    networks:
      - company-network
    ports:
      - "8923:8123"
      - "9900:9000"

ch-ui:
  image: ghcr.io/caioricciuti/ch-ui:latest
  environment:
    VITE_CLICKHOUSE_URL: http://localhost:8923  # Also tried other URLs
    VITE_CLICKHOUSE_USER: ${CLICKHOUSE_USER}
    VITE_CLICKHOUSE_PASS: ${CLICKHOUSE_PASSWORD}
  depends_on:
    - clickhouse
  networks:
    - company-network
```

2. Attempted the following connection URLs, all of which failed:
   - `https://clickhouse-db.mycompany.com`
   - `http://clickhouse:8123`
   - `http://localhost:8923` (with port mapping 8923:8123)

I verified all URLs are accessible via curl, confirming the connections work at the network level

### What did you expect?

Successful connection

### Actual Result

Despite trying multiple connection configurations, CH-UI fails to initialize with the error:

```
Failed to check admin status: NetworkError when attempting to fetch resource.
   checkIsAdmin https://clickhouse.svcpass.com/assets/index-Dx37sRon.js:551

Initialization failed: ClickHouseError: Failed to check admin status
    Ll https://clickhouse.svcpass.com/assets/index-Dx37sRon.js:538
    checkIsAdmin https://clickhouse.svcpass.com/assets/index-Dx37sRon.js:551
```

## Questions
1. Is CH-UI specifically looking for an admin user? The default user in my setup is named 'admin' but may not have admin privileges in ClickHouse.
2. Does CH-UI require specific ClickHouse permissions beyond basic connectivity?
3. Could there be CORS/security issues when running behind Traefik with SSL?

Any guidance on what specific requirements CH-UI has for initialization would be greatly appreciated.

### Browser

Firefox

### Browser Version

138

### Version

latest

**Comment by condrove10** [comment]
It would be helpful if you included the label for traefik used in your docker compose config; check this issue thread: https://github.com/caioricciuti/ch-ui/issues/57#issuecomment-2751444301

**Comment by bo-unitysvc** [comment]
I found the issue — the problem was with the Traefik entrypoint configuration.

I had mistakenly copied the labels from the earlier comment and used the wrong entrypoint:

```yml
      - "traefik.enable=true"
      - "traefik.tcp.routers.clickhouse.rule=HostSNI(`clickhouse.msipro.local`)"
      - "traefik.tcp.routers.clickhouse.entrypoints=websecure".  # incorrect
```

To fix this, I defined separate entrypoints for ClickHouse TCP and HTTP interfaces in traefik.yml:

```yml
entryPoints:
  clickhouse:
    address: ":9000"

  clickhouse-http:
    address: ":8123"
```

Then I updated the labels as follows, and confirmed everything works via `clickhouse-client` by connecting to `clickhouse-db.mycompany.com`:

```yml
  clickhouse:
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.clickhouse.rule=HostSNI(`clickhouse-db.mycompany.com`)"
      - "traefik.tcp.routers.clickhouse.entrypoints=clickhouse"
      - "traefik.tcp.routers.clickhouse.tls=true"
      - "traefik.tcp.routers.clickhouse.tls.certresolver=letsencrypt"
      - "traefik.tcp.services.clickhouse.loadbalancer.server.port=9000"
      #
      - "traefik.http.routers.clickhouse-http.rule=Host(`clickhouse-db.mycompany.com`)"
      - "traefik.http.routers.clickhouse-http.entrypoints=websecure"
      - "traefik.http.routers.clickhouse.tls=true"
      - "traefik.http.routers.clickhouse-http.tls.certresolver=letsencrypt"
      - "traefik.http.routers.clickhouse-http.service=clickhouse-http"
      - "traefik.http.services.clickhouse-http.loadbalancer.server.port=8123"

  ch-ui:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chui.rule=Host(`clickhouse.svcpass.com`)"
      - "traefik.http.routers.chui.entrypoints=web,websecure"
      - "traefik.http.routers.chui.tls.certresolver=letsencrypt"
      - "traefik.http.routers.chui.service=chui"
      - "traefik.http.routers.chui.tls=true"
      - "traefik.http.services.chui.loadbalancer.server.port=5521"
      - "traefik.http.services.chui.loadbalancer.passhostheader=true"
```

With this setup, the following configuration works as expected:

```
      VITE_CLICKHOUSE_URL: https://clickhouse-db.svcpass.com
```

But the following do not work:

```
      VITE_CLICKHOUSE_URL: http://clickhouse:8123
      VITE_CLICKHOUSE_URL: http://localhost:8923 # after mapping
```
So the root cause was indeed the incorrect Traefik entrypoint.

I also see a warning when accessing the ClickHouse UI (ch-ui), as shown in the image below, but I’m not sure how to remove it:

<img width="2268" alt="Image" src="https://github.com/user-attachments/assets/28c58be3-c042-459b-962b-bbcd4d3e703b" />

Any ideas?
